theme: jekyll-theme-cayman
title: 黄廷柳的博客
description: The Write Less,Do More
# 你发布的博客的 URL 地址
permalink: pretty
post-img-dir: /assets/img/post/

baidu-analysis: true

# paginate: 5

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "huangtingliu"

