theme: jekyll-theme-cayman
title: jekyll
description: The Write Less,Do More
# 你发布的博客的 URL 地址
permalink: pretty
post-img-dir: /assets/img/post/

# paginate: 5

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "huangtingliu"

